/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'smartsensor' at '1/18/17 2:15 PM' with Gradle 3.0
 *
 * @author smartsensor, @date 1/18/17 2:15 PM
 */
public class Library {
	public boolean someLibraryMethod() {
		return true;
	}
}
